# Generated by Django 4.0.4 on 2022-04-29 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('image', models.CharField(max_length=250)),
                ('movielink', models.CharField(max_length=250)),
                ('genre', models.CharField(choices=[('RC', 'Romantic Comedy'), ('TR', 'Thrillers'), ('DR', 'Drama'), ('CO', 'Comedy'), ('DO', 'Documentary'), ('FA', 'Family')], default='RC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('recommend', models.BooleanField(default=False)),
                ('movies', models.ManyToManyField(to='main_app.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
