# Generated by Django 4.0.4 on 2022-04-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_movie_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
