# Generated by Django 4.0.4 on 2022-05-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='Would Recommend'),
        ),
    ]
