# Generated by Django 4.0.4 on 2022-05-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_review_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommend',
            field=models.BooleanField(verbose_name='Would Recommend'),
        ),
    ]
