# Generated by Django 4.0.4 on 2022-05-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_favorite_genre_alter_favorite_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='genre',
            field=models.CharField(choices=[('Romantic Comedy', 'Romantic Comedy'), ('Thrillers', 'Thrillers'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Documentary', 'Documentary'), ('Family', 'Family')], default='Romantic Comedy', max_length=15),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Romantic Comedy', 'Romantic Comedy'), ('Thrillers', 'Thrillers'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Documentary', 'Documentary'), ('Family', 'Family')], default='Romantic Comedy', max_length=15),
        ),
    ]
