# Generated by Django 4.0.4 on 2022-05-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_favorite_genre_alter_favorite_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommend',
            field=models.BooleanField(),
        ),
    ]
