# Generated by Django 4.0.4 on 2022-05-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_review_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='recommend',
            field=models.BooleanField(default=False, verbose_name='Would Recommend'),
        ),
    ]
