# Generated by Django 4.0.4 on 2022-05-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_favorite_genre_alter_movie_genre'),
        ('main_app', '0009_remove_review_movies_review_movies'),
    ]

    operations = [
    ]
