# Generated by Django 4.0.4 on 2022-05-03 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_merge_20220502_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.movie'),
        ),
    ]
