# Generated by Django 4.0.4 on 2022-05-03 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_review_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movies',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_app.movie'),
        ),
    ]
